---
abstract: 'Photog! turns a directory tree of source images into a photography website with nested albums of chronologically sorted photographs'
author:
  - 'Jaap Joris Vens <jj@rtts.eu>'
build_requires:
  Test::Simple: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Photog
requires:
  Algorithm::Numerical::Shuffle: '0'
  Config::General: '0'
  Cwd: '0'
  DateTime: '0'
  File::Basename: '0'
  File::Copy::Recursive: '0'
  File::Path: '0'
  File::ShareDir: '0'
  File::Spec::Functions: '0'
  IPC::Cmd: '0'
  Image::ExifTool: '0'
  Image::Size: '0'
  String::Random: '0'
  Template: '0'
  feature: '0'
  strict: '0'
  warnings: '0'
version: '0.22'
